image:
  file: .gitpod.Dockerfile

tasks:
  - init: docker-compose up -d --build
    command: |
      gp await-port 8080
      gp preview $(gp url 8080)

ports:
  - port: 8080
    onOpen: open-browser
  - port: 3306
    onOpen: ignore